repositories:
    symfony-cmf:
        BlogBundle: ~
        RoutingAutoBundle: ~
        RoutingBundle: ~
        Routing: ~
        ContentBundle: ~
        BlockBundle: ~
        TreeBrowserBundle: ~
        CreateBundle: ~
        CoreBundle: ~
        SimpleCmsBundle: ~
        MenuBundle: ~
        MediaBundle: ~
        SearchBundle: ~
        symfony-cmf-docs: ~
        symfony-cmf: ~
        symfony-cmf-standard: ~
    phpcr:
        phpcr: ~
        phpcr-utils: ~
    sonata-project:
        SonataDoctrinePhpcrAdminBundle: ~
        SonataMediaBundle: ~
